services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME?:DATABASE_USERNAME not set in env}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD?:DATABASE_PASSWORD not set in env}"
      POSTGRES_DB: "${DATABASE_NAME?:DATABASE_NAME not set in env}"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${DATABASE_NAME?:DATABASE_NAME not set in env} -U ${DATABASE_USERNAME?:DATABASE_USERNAME not set in env}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  tailwind:
    build: .
    image: wongnung
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py tailwind build
    env_file:
      - .env
    environment:
      NPM_BIN_PATH: "/usr/bin/npm"
    volumes:
      - .:/app
  app:
    image: wongnung
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py collectstatic --noinput
        python3 manage.py migrate 
        python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      tailwind:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DEBUG: "false"
      DATABASE_HOST: db
    links:
      - db
    ports:
      - '8000:8000'
    volumes:
      - .:/app

volumes:
  db:
