# Generated by Django 4.0.8 on 2022-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.TextField(),
        ),
    ]
