# Generated by Django 4.0.8 on 2022-10-11 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0002_film_rating_alter_film_director_alter_film_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 14, 43, 55, 375106)),
        ),
    ]
