# Generated by Django 4.0.8 on 2022-10-13 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0004_alter_film_director_alter_film_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 15, 12, 35, 158658)),
        ),
    ]
