# Generated by Django 4.0.8 on 2022-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0007_alter_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(blank=True, max_length=265),
        ),
    ]
