# Generated by Django 4.0.8 on 2022-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0008_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year_released',
            field=models.IntegerField(null=True),
        ),
    ]
