# Generated by Django 4.0.8 on 2022-10-26 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wongnung', '0009_alter_film_year_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
