# Generated by Django 4.0.8 on 2022-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
