# Generated by Django 4.0.8 on 2022-11-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0015_fandom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fandom',
        ),
    ]
