# Generated by Django 4.0.8 on 2022-11-04 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wongnung', '0018_bookmarkable_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='items',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['content_type', 'object_id'], name='wongnung_bo_content_83f868_idx'),
        ),
        migrations.DeleteModel(
            name='Bookmarkable',
        ),
    ]
