# Generated by Django 4.0.8 on 2022-11-05 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wongnung', '0020_alter_bookmark_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fandom',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='fandom_name_unique'),
        ),
    ]
