# Generated by Django 4.0.8 on 2022-11-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0020_alter_bookmark_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fandom',
            name='id',
        ),
        migrations.AlterField(
            model_name='fandom',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
