# Generated by Django 4.0.8 on 2022-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wongnung', '0021_alter_review_content_fandom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
