name: Dockerfile testing

on:
  push:
    paths:
      [
        "Dockerfile",
        "cst-config.yml",
        ".github/workflows/dockerfile-testing.yml",
      ]

permissions:
  contents: read

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout ci-utils
        uses: actions/checkout@v3
        with:
          repository: WongNung/ci-utils
          path: "./ci-utils"
      - name: Run container-structure-test
        run: |
          cp ./ci-utils/test-dockerfile .
          ./test-dockerfile wongnung:testdrive
