name: Unit testing

on: [push]

permissions:
  contents: read

jobs:
  unit-test:
    env:
      SECRET_KEY: github-actions
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: --no-sync
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup Node.js Current
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo "NPM_BIN_PATH=$(which npm)" >> $GITHUB_ENV
      - uses: browser-actions/setup-chrome@latest
      - uses: nanasess/setup-chromedriver@v1.1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Make Django migrations
        run: |
          python ./manage.py migrate
      - name: Test and generate coverage report
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1
          coverage run ./manage.py test wongnung
          coverage report --sort=miss -m
          coverage xml -q
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
